title: Modernist theme
title: <p align="center"> Pragya Thakur </p>
logo: /assets/images/1605616459004.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pragya-thakur-29984183/">LinkedIn</a> |
  <a href="https://github.com/pragyat2611">GitHub</a>
  
  <br>   
 I have 8.5 years of experience as a software developer and fullstack engineer. 
 I am currently pursuing ML and AI program from upgrad . 
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist
